### ISSUE TITLE
Got continuous lua errors in Artaeum.

### ISSUE THREAD

**Issue by Quartiermeister** [ecizevskis/eso-map-radar#1]
Non stop spamming errors in Artaeum:
2024-05-16T21:13:36.411+04:00 |cff0000Lua Error: user:/AddOns/MapRadar/MapRadarPin.lua:91: attempt to index a nil value
stack traceback:
user:/AddOns/MapRadar/MapRadarPin.lua:91: in function 'IsValidPOI'
<Locals> pin = [table:1]{m_PinType = 45, polygonBlobKey = 1, normalizedX = 0.50501430034637, radius = 0, normalizedY = 0.4167417883873, scaleModifier = 1}, pinType = 45, pinData = [table:2]{size = 27.2, level = 120, origsize = 32} </Locals>
user:/AddOns/MapRadar/MapRadarPin.lua:374: in function 'MapRadarPin:IsValidPin'
<Locals> self = [table:3]{}, pin = [table:1], pinType = 45 </Locals>
user:/AddOns/MapRadar/MapRadar.lua:98: in function 'registerMapPins'
<Locals> pins = [table:4]{}, playerX = 0.65080261230469, playerY = 0.34051057696342, heading = 0.12137623131275, key = 30, pin = [table:1] </Locals>|r
2024-05-16T21:13:36.616+04:00 |cff0000Lua Error: user:/AddOns/MapRadar/MapRadarPin.lua:91: attempt to index a nil value
stack traceback:
user:/AddOns/MapRadar/MapRadarPin.lua:91: in function 'IsValidPOI'
<Locals> pin = [table:1]{m_PinType = 45, polygonBlobKey = 1, normalizedX = 0.50501430034637, radius = 0, normalizedY = 0.4167417883873, scaleModifier = 1}, pinType = 45, pinData = [table:2]{size = 27.2, level = 120, origsize = 32} </Locals>
user:/AddOns/MapRadar/MapRadarPin.lua:374: in function 'MapRadarPin:IsValidPin'
<Locals> self = [table:3]{}, pin = [table:1], pinType = 45 </Locals>
user:/AddOns/MapRadar/MapRadar.lua:98: in function 'registerMapPins'
<Locals> pins = [table:4]{}, playerX = 0.65080261230469, playerY = 0.34051057696342, heading = 0.12137623131275, key = 30, pin = [table:1] </Locals>|r
2024-05-16T21:13:36.816+04:00 |cff0000Lua Error: user:/AddOns/MapRadar/MapRadarPin.lua:91: attempt to index a nil value
stack traceback:
user:/AddOns/MapRadar/MapRadarPin.lua:91: in function 'IsValidPOI'
<Locals> pin = [table:1]{m_PinType = 45, polygonBlobKey = 1, normalizedX = 0.50501430034637, radius = 0, normalizedY = 0.4167417883873, scaleModifier = 1}, pinType = 45, pinData = [table:2]{size = 27.2, level = 120, origsize = 32} </Locals>
user:/AddOns/MapRadar/MapRadarPin.lua:374: in function 'MapRadarPin:IsValidPin'
<Locals> self = [table:3]{}, pin = [table:1], pinType = 45 </Locals>
user:/AddOns/MapRadar/MapRadar.lua:98: in function 'registerMapPins'
<Locals> pins = [table:4]{}, playerX = 0.65080261230469, playerY = 0.34051057696342, heading = 0.12137623131275, key = 30, pin = [table:1] </Locals>|r
2024-05-16T21:13:37.016+04:00 |cff0000Lua Error: user:/AddOns/MapRadar/MapRadarPin.lua:91: attempt to index a nil value
stack traceback:
user:/AddOns/MapRadar/MapRadarPin.lua:91: in function 'IsValidPOI'
<Locals> pin = [table:1]{m_PinType = 45, polygonBlobKey = 1, normalizedX = 0.50501430034637, radius = 0, normalizedY = 0.4167417883873, scaleModifier = 1}, pinType = 45, pinData = [table:2]{size = 27.2, level = 120, origsize = 32} </Locals>
user:/AddOns/MapRadar/MapRadarPin.lua:374: in function 'MapRadarPin:IsValidPin'
... and again and again...

**Comment by ecizevskis** [comment]
Will take a look, thanks.

**Comment by ecizevskis** [comment]
Could I please ask you to check if fix works?? 
You could open MapRadar addon folder, open MapRadarPin.lua and find method "IsValidPOI(pin)" on line 86.
Replace all method with provided code, save and do /reloadui ??

Code with fix:
```
local function IsValidPOI(pin)
    local pinType = pin:GetPinType()
    local pinData = zoMapPin.PIN_DATA[pinType]
    local texturePath = MapRadar.value(pinData.texture, pin)
    if texturePath ~= nil then
        if texturePath:find("poi_wayshrine") and MapRadar.modeSettings.showWayshrines -- Wayshrine
        or texturePath:find("poi_dungeon") and MapRadar.modeSettings.showDungeons --
        or (texturePath:find("poi_delve") or texturePath:find("poi_groupdelve")) and MapRadar.modeSettings.showDelves --
        or texturePath:find("poi_portal") and MapRadar.modeSettings.showPortals -- dolmen but also other portals :/
        or texturePath:find("poi_groupboss") and MapRadar.modeSettings.showWorldBosses -- 
        then
            return true
        end
    end
    return false
end
```

**Comment by Quartiermeister** [comment]
Done, now it works flawless. Thank you, great addon!

**Comment by edgarscizevskis** [comment]
Great, thanks a lot for testing. Now will make patch. 🙂
